# config/hook_contract.yaml

# Describes the local hook script bundled with this version of TowerIQ.
contract_version: "1.0"

script_info:
  # The relative path to the script file from the project root.
  path: "src/tower_iq/scripts/tower_hook_compiled.js"
  
  # The target package name this script is designed for
  target_package: "com.TechTreeGames.TheTower"
  
  # An explicit list of game versions this script is known to work with.
  # The application will only allow injection if both the package name matches
  # AND the detected game version is present in this list.
  supported_versions:
    - "27.0.4"
