# TowerIQ System Configuration
# This file contains only essential system settings that are required for startup
# User-configurable settings are stored in the database with sensible defaults

# Database configuration (required for startup)
database:
  sqlite_path: "data/toweriq.sqlite"

# Frida configuration (system file paths)
frida:
  # hook_contract_path removed; compatibility is determined by script metadata

# System defaults (can be overridden in database)
system_defaults:
  logging:
    console:
      enabled: true
      level: "DEBUG"
      clean_format: true # Use clean, readable format for console output
    file:
      enabled: true
      path: "logs/tower_iq.log"
      level: "INFO"
      max_size_mb: 50
      backup_count: 5
    categories:
      application: true
      database: true
      device: true
      frida: true
      gui: true
      system: false
    asyncio:
      debug_enabled: false
    startup:
      show_individual_steps: false # Only show summary unless there are errors
  #TODO: add these configs to the advanced settings page
  gui:
    auto_connect_emulator: false
    theme: "auto"
    appearance:
      theme_color: "Default color"
      interface_zoom: "Use system setting"
      theme_colors: ["Default color", "Blue", "Green", "Purple", "Pink"]
      zoom_levels: ["Use system setting", "100%", "125%", "150%"]
  connection:
    retry_config:
      network:
        max_retries: 3
        base_delay: 2.0
        max_delay: 30.0
        jitter: true
      timeout:
        max_retries: 2
        base_delay: 5.0
        max_delay: 15.0
        jitter: false
      resource:
        max_retries: 1
        base_delay: 0.0
        max_delay: 0.0
        jitter: false
      permission:
        max_retries: 0
        base_delay: 0.0
        max_delay: 0.0
        jitter: false
      compatibility:
        max_retries: 0
        base_delay: 0.0
        max_delay: 0.0
        jitter: false
      unknown:
        max_retries: 1
        base_delay: 3.0
        max_delay: 10.0
        jitter: true
  emulator:
    cache_timeout_seconds: 300
    verbose_debug: false # Set to true to see detailed ADB command debug messages
    timeouts:
      device_discovery: 3.0
      adb_command: 10.0
      adb_connect: 2.0
      adb_devices: 5.0
      process_communication: 5.0
      frida_connection: 3.0
      frida_injection: 2.0
      kill_process: 3.0
  frida:
    timeouts:
      queue_get: 2.0
      detach: 3.0
      force_cleanup: 1.0
      server_kill: 1.5
      server_wait: 1.0
      server_responsive: 15
      server_shell: 5.0
      server_start: 3.0
  database:
    backup:
      enabled: true
      backup_dir: "data/backups"
      retention_count: 7
      interval_seconds: 86400
      on_shutdown: true
      compress_zip: true
      filename_prefix: "toweriq_backup_"
  grafana:
    enabled: false
    bind_address: "127.0.0.1"
    port: 8080 # Changed from 8000 due to Windows port exclusion range conflict
    allow_read_only: true
    query_timeout: 30
    max_rows: 10000
