# TowerIQ System Configuration
# This file contains only essential system settings that are required for startup
# User-configurable settings are stored in the database with sensible defaults

# Database configuration (required for startup)
database:
  sqlite_path: "data/toweriq.sqlite"

# Frida configuration (system file paths)
frida:
  hook_contract_path: "config/hook_contract.yaml"

# System defaults (can be overridden in database)
system_defaults:
  logging:
    console:
      enabled: true
      level: "DEBUG"
    file:
      enabled: false
      path: "logs/tower_iq.log"
      level: "INFO"
      max_size_mb: 50
      backup_count: 5
    categories:
      application: true
      database: true
      device: true
      frida: true
      gui: true
      system: false
    asyncio:
      debug_enabled: false
  gui:
    auto_connect_emulator: false
    theme: "auto" 