# TowerIQ Main Configuration File
# This file contains all non-sensitive configuration settings

app:
  name: "TowerIQ"
  version: "1.0.0"
  debug: false

logging:
  level: "INFO"
  console:
    enabled: true
    level: "INFO"
  file:
    enabled: true
    path: "logs/tower_iq.log"
    level: "DEBUG"
    max_size_mb: 50
    backup_count: 5
  sources:
    enabled:
      - "MainController"
      - "DatabaseService"
      - "EmulatorService"
      - "FridaService"
      - "GUI"

database:
  sqlite_path: "data/toweriq.db"
  sqlite:
    encryption_key: "default_key"

emulator:
  adb_path: "adb"
  connection_timeout: 10
  package_name: "com.TechTreeGames.TheTower"
  activity_name: ".MainActivity"

frida:
  server_port: 27042
  script_path: "scripts/"
  signature_validation: true
  manifest_url: "https://github.com/bdeland/toweriq-hooks/raw/main/manifest.json"
  public_key_path: "resources/public_key.pem"
  hook_contract_path: "config/hook_contract.yaml"
  
monitoring:
  default_state: "NORMAL"
  high_resolution_interval: 100
  normal_interval: 1000
  
gui:
  theme: "dark"
  window:
    width: 1200
    height: 800
    min_width: 800
    min_height: 600
  auto_connect_emulator: false 